# PlatformIO pre-build script: writes include/build_info.h with the build time.
# `pio run -t upload` always builds right before flashing, so this is also the
# upload time shown on the System page. Only web_server.cpp includes the header,
# so a new timestamp recompiles just that file.
import datetime
import os

Import("env")  # noqa: F821 (provided by PlatformIO)

path = os.path.join(env["PROJECT_DIR"], "include", "build_info.h")  # noqa: F821
stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write("#pragma once\n// Generated by tools/build_info.py on every build. Do not edit.\n")
    f.write(f'#define BUILD_TIME "{stamp}"\n')
